spring:
  docker:
    compose:
      enabled: false
  application:
    name: 'slurp-backend'
  profiles:
    active: '@activatedProperties@'
  banner:
    location: file:banner.txt
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5         # Connections always available
      idle-timeout: 30000
  jpa:
    database: postgresql
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC
server:
  servlet:
    context-path: '@project.contextPath@'
