spring:
  docker:
    compose:
      enabled: false
      file: 'compose.@activatedProperties@.yaml'
      lifecycle-management: start_and_stop
  datasource:
    url: "jdbc:postgresql://localhost:5432/development"
    username: myuser
    password: mypassword
project:
  security:
    jwt:
      expirationInMilliseconds: 604800000     # 1000 ms * 60 s * 60 m * 24 h * 7 d
