spring:
  docker:
    compose:
      enabled: false
      file: 'compose.@activatedProperties@.yaml'
      lifecycle-management: start_and_stop
  datasource:
    url: "jdbc:postgresql://localhost:5432/development"
    username: myuser
    password: mypassword
